[package]
name        = "alif"
version     = "0.1.0"
edition     = "2021"
authors     = ["AnmiTaliDev <anmitalidev@nuros.org>"]
description = "Alif — formal proof verifier"
license     = "GPL-3.0-only"

[lib]
name       = "alif"
crate-type = ["rlib", "cdylib"]

[[example]]
name = "alif"

[dependencies]
logos     = "0.14"
chumsky   = "0.9"
ariadne   = "0.4"
rustyline = "14"
